---
name: Example
version: "5.0.1"
slug: example
description: Ericsson2506 Home Assistant Example Add-on
url: https://github.com/Ericsson2506/Addons
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
  seconds_between_quotes: 10
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
